export const add = require('media/add.svg')
export const remove = require('media/remove.svg')
export const close = require('media/close.svg')
export const menu = require('media/menu.svg')
export const arrow = require('media/arrow.svg')
export const search = require('media/search.svg')
export const more = require('media/more.svg')
export const burst = require('media/burst.svg')
